### PR TITLE
Allow multithreaded workers + general spring cleaning.

### PR DESCRIPTION
**Pull request by sengi**
Allow consumers to specify a thread pool of size greater than 1 and/or a maximum unacked messages limit of greater than 1. These two levers may help us address e.g. the [low CPU utilization](https://grafana.eks.production.govuk.digital/goto/n1hhtHBIg) (and throughput per worker replica) in search-api-v2.

No change in default behaviour; the defaults remain the same as the previously hard-coded values.

Also a bunch of cleanup:

- Remove some remnants of the (already removed in 4.0) "batch consumer" functionality.
- Remove disused support for statsd. (https://github.com/alphagov/search-api/pull/2889 removes the last remaining call site.)
- Tidy up the README.

See commits for more details.

### CODE REVIEW

**Review by richardTowers — APPROVED** [review]
Looks good, thanks for this - nice cleanup

**Review by csutter — APPROVED** [review]
Oooh this is nice, especially given that most (all?) of our workloads in downstream apps are probably IO-bound anyway ❤️

**Comment by sengi** [comment]
In theory you could approach it quantitatively with Little's law and whatnot, but tbh I'd probably just go with empirical trial and error i.e. just keep doubling it until you start to see diminishing returns.

I'd keep the defaults the same between environments so you're less likely to get surprises. You'll want to make it [tunable](https://github.com/alphagov/search-api-v2/blob/b0fd78b/lib/tasks/document_sync_worker.rake#L22) anyway, not least so you can easily turn off concurrency if it's getting in the way of debugging a test or the like.

I'd also set the max-in-flight (which Rabbit confusingly calls "prefetch") the same as the concurrency, all else being equal. I figured it would be presumptious to actually tie them together, but it should be a pretty good rule of thumb to start with them the same.

**Comment by kevindew** [comment]
@sengi thank you

**Comment by sengi** [comment]
yw!

**Pull request merged**
